
[Setup]
# 指定安装程序其它参数 Begin
# 指定程序语言
;LANG_ID=2052
;DVNf4VC4rmVLjsRLf4zlaQ..=5Cg7NICz9dOjthrFulp2ZA..

# 指定程序版本号
;BUILD_VERSION=12.1.0.23542
;tzB-HAHJJxzGdJoZU4_SVQ..=nzMVo6EEfEe5j5EG-dZb2Q..

# 安装注释，意义不明
;installationComment=WPS Install Application
0nh27kXZ2kOnN6zougLiHytcq8xOLFatehtYRhTu44M.=ZhuHKyJuePYGtqCJFUwSaJ_2MNTQcOEWC1UCEqNh3Uc.

# 指定安装程序其它参数 End

# 外部安装项目相关 Begin
# RelativeDir 参考：INSTDIR 安装目录 FONTS 字体目录
;InstExeCount=0
;tGvQqGneWtXSq8PHj1GGYw..=-oqsL74hpiah3RGyR6hniw..
;FinishActionFile=oeminfo\oem.exe
;s0HRbVjEZjYfiVdjuCC4AtH_HWpeBrG_9hpfdL1oM7Y.=Mr0uI6lvRC8yp2Zb511d1w..
;FinishActionParameter=
;tXzAssDBY8r4nAPajcEuJOi3Thi-aRRZ6V265pF7GF4.=
;FinishActionWait=1
;UkggKDEPzbNL9aajyxDulNH_HWpeBrG_9hpfdL1oM7Y.=19yByiwfu3JHLy74jX23aQ..
;FinishActionFile2=oeminfo\oem.exe
;s0HRbVjEZjYfiVdjuCC4AvAVsJNRFJl5AIDJKFP8r8A.=Mr0uI6lvRC8yp2Zb511d1w..
;FinishActionParameter2=
;tXzAssDBY8r4nAPajcEuJD-X9t960fzG83XIUcxixiI.=
;FinishActionWait2=1
;UkggKDEPzbNL9aajyxDulPAVsJNRFJl5AIDJKFP8r8A.=19yByiwfu3JHLy74jX23aQ..
;FinishActionFile3=oeminfo\oem.exe
;s0HRbVjEZjYfiVdjuCC4An2tO2bwMQ-plDCPWGDZjx0.=Mr0uI6lvRC8yp2Zb511d1w..
;FinishActionParameter3=
;tXzAssDBY8r4nAPajcEuJCFvoMH6HUfryy3f2Kmwzs0.=
;FinishActionWait3=1
;UkggKDEPzbNL9aajyxDulH2tO2bwMQ-plDCPWGDZjx0.=19yByiwfu3JHLy74jX23aQ..
;FinishActionFile4=oeminfo\oem.exe
;s0HRbVjEZjYfiVdjuCC4Aq-MlT2vz53kbaCW_BdKnc8.=Mr0uI6lvRC8yp2Zb511d1w..
;FinishActionParameter4=
;tXzAssDBY8r4nAPajcEuJA3PhlZcvC5NWksFMu84FpA.=
;FinishActionWait4=1
;UkggKDEPzbNL9aajyxDulK-MlT2vz53kbaCW_BdKnc8.=19yByiwfu3JHLy74jX23aQ..
;PlacedDir5=
;FinishActionFile5=oeminfo\oem.exe
;s0HRbVjEZjYfiVdjuCC4AuXSR3Aomc7DgoRTTFRsW2w.=Mr0uI6lvRC8yp2Zb511d1w..
;FinishActionParameter5=/exefile='office6\ksomisc.exe' /fileparam='-showallinone' /ShellVarContext=current /RelativeDir=INSTDIR
;tXzAssDBY8r4nAPajcEuJMgvpYolwPXJirPl-cnTsI8.=
;FinishActionWait5=1
;UkggKDEPzbNL9aajyxDulOXSR3Aomc7DgoRTTFRsW2w.=19yByiwfu3JHLy74jX23aQ..
# 外部安装项目相关 End

# 外部卸载项目相关 Begin
;UninstExeCount=3
5f1WKPZ1mdCcIDzCkK6EoA..=19yByiwfu3JHLy74jX23aQ..
;UninstActionFile=office6\cfgs\oeminfo\VBA_Uninst.exe
SW5xGPWlfmhJZWHMWIpPoNH_HWpeBrG_9hpfdL1oM7Y.=sShVASi1PI4fUCSdg1nOmkg9xHd-gZFvlj_4dwT_4vzHSBulxDroRYUXuXPncXkt
;UninstActionParameter=/VERYSILENT /NORESTART /SUPPRESSMSGBOXES
LS8INXVJBL4FdaLzoJnygui3Thi-aRRZ6V265pF7GF4.=iDeqCdhbMgMaLTLB8q37avnPqfpGAKAjXblVpcRp8Vwc0QxnWz3dkduzH9T1sLxo
;UninstActionWait=1
1buigYQjiYg5clo31kpyLNH_HWpeBrG_9hpfdL1oM7Y.=19yByiwfu3JHLy74jX23aQ..
;UninstActionFile2=office6\cfgs\oeminfo\oem.exe
SW5xGPWlfmhJZWHMWIpPoPAVsJNRFJl5AIDJKFP8r8A.=sShVASi1PI4fUCSdg1nOmp2jPcN_dYdjJiORAoqnNeU.
;UninstActionParameter2=/ShellVarContext=current /RelativeDir=INSTDIR /rmdir='oem' 
VcF8YcFUZZAyb1lw_T0vKT-X9t960fzG83XIUcxixiI.=_KFAi5Cxrod1E3efC2LD0t67x8--j6tahUFB3XDH-NV1GalbCIyaIylgM-_iEpgZ00uczhq8w-pjdlsX47kQ4Q..
;UninstActionWait2=1
1buigYQjiYg5clo31kpyLPAVsJNRFJl5AIDJKFP8r8A.=19yByiwfu3JHLy74jX23aQ..
;UninstActionFile3=office6\cfgs\oeminfo\oem.exe
;UninstActionParameter3=/ShellVarContext=current /RelativeDir=INSTDIR /rmdir='office6\cfgs' 
;UninstActionWait3=1
# 外部卸载项目相关 End

;00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000