;/DWPS_SETUP

# WPS Office 自定义程序功能配置文件
# 雨糖科技 以爱敬献

[Feature]
;5HsDS8UAjZnKSU9I2xbCubqA10=KHsDS8UAjZn4U3A385v-NVsE10
;pDKIJxJrennKSU9I2xbCurSc10=pDKIJxJrennk99gTmjC7TE8V10

[UserAnalysis]
IsShowUpdateDlg=0

[Auth]
KSNUpdateServerUrl=http://0.0.0.0
;LicenseServerUrl=http://wps.mycustom.server/account
TotalTrialDays=2147483647

[Server]
;IntranetPluginsICServer=http://wps.mycustom.server/xva/v1/plugin/stat
;QingUrl=http://wps.mycustom.server
;CustomUpdateServer=http://wps.mycustom.server/wpsoffice/updateserver/update
;CustomAutoNomInfoSvr=http://wps.mycustom.server/wpsoffice/wpscollect
;InfoCollectServer=http://wps.mycustom.server/wpsv6internet/infos.ads
;QInfoCollectServer=http://qinfo.wps.cn/qingoffice/infos.ads

[Product]
VYA4oteJ0HkPSeHxKPW7Uuh_BiSHT7CEmwKUIOPcuI8.=_jMwaHXGroRf7jge76bnfN36TxAhyIfPj0FNGpd2nNVHAob0_KH010p3m5MfO4JdLu_gdmCRLUrz_8_cMDX9R0UvEhOFEfvhkW52KZE17GZvzqLFzOFK0ALbnaXQdFqtF2qsp6fjLIEtpB9bHjja0bnADzZne3gFTFoIk8y9Gbn2rXxqw9AJyDo3B8iyXG-hUL5V5j5wa6EbRRMeMk4LNBFKikH1NUy_mNzyybyMDaewI7f5ONphy7d-HsSrutfB5Q_ka8I1v_VUsghjOZrYd19OMgnofZBf-fJ076mB1BewGR-yDAdNIDChWDeXnGSzxRP6cTZmBmCZAdpfy31vqrp6k0bOdv4oNSUg_jdD0vIHit_eGjU7fTGJ-CRWTY0aFAn1vPl4xc6d00QkSXSslWCdddmyuPyXYhSX7PAWMHN5ApJpLFbX5i1xHDFnZijakhXwCyaP0eVkIUnuLkXIvCq03HG9lkZ1dHcZIdhooivwqmsI7lKRhXltnRiYXwP0Nr_5pGMP6vh_S4oJ6z54BYZDrSTHAw1UL_JaD_QT1aMoedO8EFA3L-D8XuyE3m1m

[Support]
Support2016SN=true
;Update=false
DisableUpdateCheck=true
;Prometheus=false
;WPS365FeatureEnable=false
;WPS365EnterpriseGuide=false
;IntranetVersion=true
;IntranetDrive=true
;ForceIntranet=true
;EnableNetwork=false
;EnableCloudDocs=false
;EnableCloudService=false
;NotStartCloudSvrBroadcast=true
;EnableOnlineCooperation=false
;OnlineFeatures=false
;OnlineWithoutCloudDoc=false
;IsDisableLoadCloudDocLib=true
DisableUpdateExternalDataLinkDialog=true
;CellphoneControl=false
;CloudDocOnline=false
;SupportNewToCloud=false
EnableWPSOfficialWebsite=false
WeChatCustomerService=false
ShowWeChatQRCode=false
TouchUiMode=true
;FileRoaming=false
;DocTabRoamingWorkSpace=false
;CloudLink=false
;FileMenuDocumentHistory=false
;DisableFeedback=true
;FeedbackByMailInMenu=false
;UseRoaming2015=false
EULAPopup=false
;DisableOnlineUserAgreement=true
;supportTeamDoc=false
;DisableAutoRoaming=true
;HideFreeTemplate=true
;FileShareMode=false
;EnableAccount=false
;WPS365Login=false
WPS365ForceLogin=false
forbidEditInForceLogin=false
QingForceLogin=false
QingShowLoginWindowOnStartup=false
;WPSCloudLogin=false
EnableProcessonMind=true
EnableProcessonFlow=true
OCRTool=true
IsSupportPhoto2pdf=true
;EnableDocerShop=true
XiuTang=false
;EnableEDUCourse=false
;MulticlipboardEnableAccount=false
;DataRecoveryMaster=false
;DisableWpsAcademy=true
;DisableSmartForm=true
;NewFromOlineTemplates/TaskPane=false
;NewFromOlineTemplates/NoTabPage=false
;NewFromOlineTemplates/FileMenu=false
;DocerEntrance=false
;DocerEntrance/WorkSpace=false
;DocerEntrance/DocTabbar=false
DocPermission=true
EnterpriseDocpermission=true
;EncryptWithoutAccount=true
;EnableSecDocRightsList=false
;HideRightlistForNonSecdoc=true
EnableNormalEncryption=true
EnableCoreEncryption=true
;SupportDocAuthenticate=false
;OnlineSecurityDocument=false
EnableCustomFormatSecurityDoc=true
;SaveasSecurityDocByAPI=false
;SaveToSecurityDocDirectly=false
SmartOfficial=true
NeedPrivacyPolicyPopup=false
;DisableGlobalInfoCollect=true
ReportAllInfoToDataWarehouse=false
CommandTriggerInfoCollect=false
GoogleAnalytics=false
IcibaWakeupInfoCollect=false
EnableSNInfoCollect=false
EnableProductIdentifierCollect=false
CollectAuthInfoOnStartup=false
;EnableAppsCollect=false
;DisableFileCollect=true
;QingLoginOfflineMode=true
;EnableTempleteShop=false
;EnCldSvrOnEmbed=false
;CloudFonts=false
;CloudFileMgrInUserCenterMenu=false
;WpsAssistOnlineTemplate=false
;EnableOnlineFunction=false
DisalbeUpdateInfoCollect=true
UpdateSchdTaskByKsolaunch=false
;DisableCollabration=true
;FileRoamingShareLink=false
ReportGetIpAddress=false
;DoNotSupportMessagePush=true
;CloudStorage=false
;DisableShareDocs=true
;EnableClientCooperation=false
;DisableMessagePush=true
;DisableOnlineMeeting=true
;HideCloudSpace=true
;SupportCloudPushMsg=false
ShowCustomerServiceQR=false
;isSupportDocCloudSync=false
DisableSNOverNumberLimit=true
ForbidEditInLoginSNAuth=false
;OnlinePictures=false
;WPSDriveEnabled=false
;DisableCloudSyncSetting=true
EnablePdf2WordV2=true
ShareMemoryAuthForPDF2Word=false
