;/DEP_PDF_SETUP /DUSER_LEVEL 

# 金山 PDF 自定义程序功能配置文件
# 雨糖科技 以爱敬献

[Feature]
sQD2Rt_mwGqKSU9I2xbCuDGc10=cQD2Rt_mwGqk99gTmjC7T-YR10
pDKIJxJrennKSU9I2xbCurSc10=pDKIJxJrennk99gTmjC7TE8V10
;bxrrBrk62yXdi014TXG8PRUC10=qxrrBrk62yXL6asfG-MCpuio10
dv6LsqiMMNQXlduWtVwfpKcQ10=dv6LsqiMMNQHDH_t7GU4EymD10
GitgscnaeT-KSU9I2xbCubXG10=HitgscnaeT-k99gTmjC7T-_w10
ZYTJwCQFjyrKSU9I2xbCuXrj10=ZYTJwCQFjyr4U3A385v-Nx9n10
xn3QfP-XIpyKSU9I2xbCubad10=hn3QfP-XIpyk99gTmjC7T6IF10

[UserAnalysis]
ibrX5N9rjShv8Z72td8Kbw..=-oqsL74hpiah3RGyR6hniw..

[Default]
z60NQ8VZ49fwhv5l11TIHb32CDiRrHh9nniG-CpvHCI.=PE0gO7ABWXtqilYFaKIjElKT07BC3c8amMtJSJVCdeE.
k5tepQ0nlKIkMSSlpo25sgWE0lfqSiJ6Q4idIVPksHE.=MqWMu-z57p38FUnAn7N2GL4kerOMC4ha49cBkVOK4C8QBchjPIQFExPP1pHu9t41
aNWpXK2-1EFfdvEZ9lzqaaxLjCZBZCjZG3TWk4jPOd0.=7yn2fWrvyoRyah6W1i3g8C0ngK2jVmOpiNJwzVuMkBzgP-H7-sEExPZJ0dbAygpW
BVRJQ1boXVRjiyWPazXPx9H_HWpeBrG_9hpfdL1oM7Y.=r0Cv-1Za4Wm1hLZBjkrd_vPisbsDFedPvWwc0De4kWE.
gZkJQLEh2hRCsevlB4Iy9Q..=mIW9Qa78rv7hDxEr2CEwonQL6bD27P39XePZljtjdjM.
Kw1y9Ygkqqvjn09mw2tMvFbMpY8VRL_bot55_GlTrXY.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
kXbwKhKQlmTcFGuJDIzAZg..=ygQHWGTWeZ3EoEz7cQDxFb09UAgtJpftgzlwhJrZ5zVOxpAntI-xuffYKON4GRj89YgLH6cNtN7l6FX50m4jFA..
1aIB2vJXgrxh8GSk77-HcA..=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
QC_N867elcpV-_RdnpQPuzQxJkUB5vPWag3HEA6HyVQ.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
4gYZnHosij-tU9PhKV3te9H_HWpeBrG_9hpfdL1oM7Y.=702ObsCGwmG1pCNHZV7FMNH_HWpeBrG_9hpfdL1oM7Y.
Lyz1avnQX2g9az5rzLvAgw..=702ObsCGwmG1pCNHZV7FMNH_HWpeBrG_9hpfdL1oM7Y.
HJ9bGnalLrRztuKSh4RDSQ..=702ObsCGwmG1pCNHZV7FMNH_HWpeBrG_9hpfdL1oM7Y.
MWE1XCYd_lJOTHMCAJy0rtH_HWpeBrG_9hpfdL1oM7Y.=ie6xZbOxaw28sGHIgDnZkw..
UYkcgdnWkt83qzN9kiTPsw..=TWHxrDwZHEOEA3Z28UWtu4KoXcCeH3nRYjgp08j23evR-h1qXgaxvvYaX3S9aDO2
KDJoWsTvnvQdLi9hXN3B8d4kOx_f68XEGanq0fbxhFc.=702ObsCGwmG1pCNHZV7FMNH_HWpeBrG_9hpfdL1oM7Y.
9agMQof_EOMtSzh8XfKK1Q..=w9i9uWkc6RN4cPeNd-bnm_ME1t71KVoDEQrrOcqz-f3R-h1qXgaxvvYaX3S9aDO2
XAoSmN4Dk8PJG50puLaNe-iIrz2EFPJoaiSwWCbv1_A.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
FVOPKYNb5aR8Z9wAKwqn_w..=TWHxrDwZHEOEA3Z28UWtu4GTYSIZfSqR_rPA2SGcE5U.
b8Jbsz0es6dVZTUs41-RotH_HWpeBrG_9hpfdL1oM7Y.=ie6xZbOxaw28sGHIgDnZkw..
lkePwfLQhd5Jl9UD6plrktH_HWpeBrG_9hpfdL1oM7Y.=ie6xZbOxaw28sGHIgDnZkw..
fjdWgL7F7Sb6AYnB1-9IVwudz9eOHfy4fF_K3O8EI5Y.=ie6xZbOxaw28sGHIgDnZkw..
fjdWgL7F7Sb6AYnB1-9IV2iI59N09aVUn_W5K-I66Dc.=ie6xZbOxaw28sGHIgDnZkw..
kaq6eCtrh8OU3Lhp4VVrhOwDpWzqHZISSud12G9US5o.=9HBSUHwm9OKGJjuE6z2A_oKoXcCeH3nRYjgp08j23evR-h1qXgaxvvYaX3S9aDO2
jko0IwcTvUkzCbPvis6rUIxF_x6CEcMTNTiM8kp_W9A.=yWk4LEaAedM-vN7LeOyupjSCiIj2-axUfWaADmFdCsg.
yBlP3IMBMHTWHWhPWb4phptKvHWw-Duvv41iSy5T0uo.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
G5Q0nJ54XBLFEjUFIrYFq0UI5s_tAz7i2RQadcFFTAQ.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
iWJdUhmuEnlMZpX4RpvBi79Vz6S3RjIU5OcXpKELsiY.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
Rl0Iad1EpFZJvBDNSTikEBnaP3gmfKQ8VsT3CZClzu4.=702ObsCGwmG1pCNHZV7FMNH_HWpeBrG_9hpfdL1oM7Y.
;qEZRk60SoDS5eLup5Dj5Og..=UK4BcChW4W6ZZh8AnzOmr6UsvRHAEEFSx_IHUu6r6GHzm2dJsxsYQM8cuoaSVmhrRwdDekhzKJLHT2Fse__bJQ..
nXSvj8wAZR1s_DOIjCIMkguCTrKEmxo5_kSkX2jRDb0.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
Gn2PH3_a-6EaPMI2Phnf0w..=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
;SnljCZwg8OrhebXPhhOICg..=yWk4LEaAedM-vN7LeOyupjSCiIj2-axUfWaADmFdCsg.
QnGGPnoqMx4etU5SzylTcg..=r77BKyKyOZFBqWLUNDP5qKFwcpcCcvfSsEq_JWZ1KAE.
A7NXnmJ7upQqUk0vupqQbjqntAaO02Gf3E9c5i7xfxE.=RHarrZVt7qY6mU4RC_iYcSPTU1aWWKLno2RmsjUq197LMB9EcsTQVXTpI2IDp0vg
onEdS9pL4D7i6-1ieiNmR5Tzazhjfv4IJo39il7gn-0.=702ObsCGwmG1pCNHZV7FMNH_HWpeBrG_9hpfdL1oM7Y.
;bnCXYbHUHXz5DbMnnQLqO7K2voqJstRHE5QuicWlKQo.=702ObsCGwmG1pCNHZV7FMNH_HWpeBrG_9hpfdL1oM7Y.
eyVCIEMRZ9qQt7VFVdOIeA..=mKty-u-3M5Z-dSp3IlTLShu9CvYLwZs_LVzhyUrC5JSlDQQS4OU6U6TrC1u02fni91XmCxrv3tGhdSvPFIhZN4KoXcCeH3nRYjgp08j23evR-h1qXgaxvvYaX3S9aDO2
nSoZmRX36k5dpaK7O-onGA..=ie6xZbOxaw28sGHIgDnZkw..
bF2rjlqAvEu4_BBrgFtjpl075uGfpvtFKU_dqU-vYGE.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
XqQHnvwcS8l7m95VH9Vnpw0kJno4afvyCc-xhzQIjLc.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
mCNo9NSV3YS2UPrzFI1dPh8GUa0P-TLBJ8L2WiYUWbQ.=RCNDeG1VOFTWl-v2E7sHZg..
8Tc5sAqTCE0pV4GSqT70IaPF7DBUzsTPVV7ADnnq7a8.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
OmFKUaO7c1RBfKqsytolQtBkoA3q6QJCORWC_gmRMuc.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
NKT5uoqxMFRnWWO1tyBZa1S1FGHEv9gRLbP42o0ZmyE.=702ObsCGwmG1pCNHZV7FMNH_HWpeBrG_9hpfdL1oM7Y.
U_EuJ6C5EiIUMgEhgh-Www..=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
7s_DCz20IgUvwkBaBDIcFB5Wg2tppi_OqoC2EMcKMS0.=OEldPPKmtyRxT2fETlbP_w..
F9rcrmL-Sol1-EUDHavG8Q..=TWHxrDwZHEOEA3Z28UWtu4GTYSIZfSqR_rPA2SGcE5U.
;YGPOJZVYrru6P2ptZYAcvA..=702ObsCGwmG1pCNHZV7FMNH_HWpeBrG_9hpfdL1oM7Y.
sQPhupor1ZzsWTvjUo5sOw..=w9i9uWkc6RN4cPeNd-bnm_ME1t71KVoDEQrrOcqz-f3R-h1qXgaxvvYaX3S9aDO2
vDZMZCkRwvnDbQ18eTWRJyV1_uo8xVu3L0StVW0auLU.=702ObsCGwmG1pCNHZV7FMNH_HWpeBrG_9hpfdL1oM7Y.
JuGhh9e8lVGlqe6_iBMBQhw4cgQP_aqsrL3azzCMIZI.=w9i9uWkc6RN4cPeNd-bnmw7ER3Kw7he5BKeRYFu43OdByEEMc8Kb5_w27wFQMPiNPwN01ENCkKakGGbLutk7i8swH0RyxNBVdOkjYgOnS_A.
JuGhh9e8lVGlqe6_iBMBQk8jf7rLdnUbjAK7CG5kOTo.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
UfliTJ-9qgxMZcmCvbxh8swLBaLCQs4KKIhCltC4P44.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
-E8nq17vrEsqZr1wWNaPWA..=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
QiFEq3uDyW9qiz1d2ap4yg..=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
0nfLXy4T5VPti_UF_EI08enyRWaPiU77GmNx4iqr7Jg.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
Oqv3FpSngXuOBNdpECHTdTdz3jgXMRRxfemJEIGjanI.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
UA2o29F1TbglN8Y8tpDoVhw4cgQP_aqsrL3azzCMIZI.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
Lod6T38F9VlN-ZBjYxbxAKEjeAq-uQ916LYXdB0LS_k.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
uEgcBJY_hOQRdAzPPCBq2w..=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
zoPWQmn6Z0LTFoqkv4RVMHQ6CCH8oIpZRblMsHZYeEw.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
k5tepQ0nlKIkMSSlpo25skhhGqJ-BG0cpgJBibYeSrg.=j7MUQ1g5k7MLYrojjJ4Rpg..
mZE5XcN5mlA4djkmeMTf8P7HAW6QNQOHnoC95o5Cb88.=702ObsCGwmG1pCNHZV7FMNH_HWpeBrG_9hpfdL1oM7Y.
SUx11DETsKtnrLvHXbtqGYWASHJ9ud1ZAC2SGeTR39k.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
HTPDtVFg3n-uoBiUYsZZ0Rw4cgQP_aqsrL3azzCMIZI.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
xmDcnLCCqsiQB7JDQ5tq9mE6YtRTVD52Du8DPuXGcNo.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
1-ejEP5CvwgfIKW56S9YKQ..=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
FyJAVvXUB3uWJ29oelB6wV0dIgxQG75Mwn9_MCsUHjs.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
QWSL2ahPKlEH1MO0qoZMDSbjhWSGeNMgGE_n8w75PeQ.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
Ku2LdIH7f6ceAGFb8wdoXYqUCLe4wjOwwOuTwbcaguM.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
mAVUcJdvxZNjOetV_O5CzkO7M1q0lbLRrbuZj-1BejY.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
o9x1WusaZxOQa3gABrGXhaWsigr_9qkhrBhHu6PYTN4.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
-2X3fqtQGMBwG2aDt45oFQ..=FHVE4p_WPhmruJAo0YcxcQ..
Bt_EfXkILBoLRyxMJ_-K25gYY0Dryr9qCsmg7f1cTP8.=m0383R-ZmwhtrwegU9LQjFa_FSWJCQo5tn_nSFWaGZw.
E9GR8NNzn64U9AUuthzmXg..=4T_V9wWKrCv0UIypuOYX5dzr38Mk27SWaShJ8gXDrfY.
nC2fSYecLy_9r7tFUg98lb32CDiRrHh9nniG-CpvHCI.=702ObsCGwmG1pCNHZV7FMNH_HWpeBrG_9hpfdL1oM7Y.
xmVhQzo_PbDxkeMc5_YIhXzuahAhUraTjAcTrYruBbM.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
71MC85-h0G2c3JdAuP3ogBw4cgQP_aqsrL3azzCMIZI.=702ObsCGwmG1pCNHZV7FMNH_HWpeBrG_9hpfdL1oM7Y.
aPPLVbnszQmhAuhvIk0LF3qDqRKS-RoHOjkOgSPPje4.=ie6xZbOxaw28sGHIgDnZkw..
;P8SGa0nHvWj422dTluxD5w..=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
jVKukLaQmMyts6dCjE94RqWoQ73lB3QfplcrpO-Supg.=w9i9uWkc6RN4cPeNd-bnm_ME1t71KVoDEQrrOcqz-f3R-h1qXgaxvvYaX3S9aDO2
0Oc4qBcQUpSd5VTTzYUUnvM5m2YHrhe15evNO3j9g4vR-h1qXgaxvvYaX3S9aDO2=ie6xZbOxaw28sGHIgDnZkw..
;AbKu3IFnhIihjFmRl0auaw..=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
iG8G0kGtwSCy0Tls7t6D4A..=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
zf0n10dbHpUDy8htzsetLNH_HWpeBrG_9hpfdL1oM7Y.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
MWMVK5L_cqZn6Km3Uw_dQ95vE2mhl0xnPalVCKUXDGw.=yWk4LEaAedM-vN7LeOyuppeTKGJd7iplAyMlf3PDCAo.
3InmOen2O4CmERB7A2HNaQ..=OnSGfbqK53HLh2eaRdibyw..
-o47WgnyeEg6jftex_y6vA..=OnSGfbqK53HLh2eaRdibyw..
r0TxOS8WmW5bDoQbudGZfaPkaM2f3PRTEKs7S9QLwqs.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
NHadt5sVBRKkMgL74FlEdqPF7DBUzsTPVV7ADnnq7a8.=ffLvKNDsC4WhYxhCc0vlQbEqDSkE7pEZXxaYFdGMkQUYj3dW3GF4sQk5CU7B9Ze7bEat0TxLFcC9rD1zfMu-Fw..
NHadt5sVBRKkMgL74FlEdn7r0NJhaaGkLd-k4LzIlDw.=w9i9uWkc6RN4cPeNd-bnm-PisbsDFedPvWwc0De4kWE.
zLGc9_HP03AzZqLXUbfVqB1ixJW_XaE2CEQFmsAwUCQ.=ie6xZbOxaw28sGHIgDnZkw..
jVKukLaQmMyts6dCjE94RqWoQ73lB3QfplcrpO-Supg.=w9i9uWkc6RN4cPeNd-bnm_ME1t71KVoDEQrrOcqz-f3R-h1qXgaxvvYaX3S9aDO2
0Oc4qBcQUpSd5VTTzYUUnvM5m2YHrhe15evNO3j9g4vR-h1qXgaxvvYaX3S9aDO2=ie6xZbOxaw28sGHIgDnZkw..
VuzFi3AEIPc3umvQzr6Eu43Ryutl5aIZNSEZzFVcYTY.=7yn2fWrvyoRyah6W1i3g8O74YsdvLemkWeoabFdrjaIF-bQCvegagwhVD7QijlI6bE6zB199oChXbVw5HA4TXA..
